from django.urls import path
from .views import (add_product, 
                    edit_product,
                    product_list, 
                    products_formset_view, 
                    icecream_form, add_dz26, add_course, course_modelformset, course_with_lessons_view, user_info, for_staff, 
                    half_admin, books_list, productsearchform, test_transaction, vote_view, upload_image, serve_file, list_files, 
                    photo_list, delete_photo, upload_photo, upload_file, list_filess, upload_low_level, check_product, create_product,
                    ProductListCreateView, product_list_cached, user_list, task_detail, task_list, create_user, TaskDetailView, 
                    TaskMetaView, ProductListView, get_token_manual)

urlpatterns = [
    path('booklist/', books_list, name='bookslist'),
    path('halfadmin', half_admin, name='halfadmin'),
    path('userinfo/', user_info, name='user_info'),
    path('forstaff/', for_staff, name='forstaff' ),
    path('list/', product_list, name='product_list'),
    path('add/', add_product, name='add_product'),
    path('edit/<int:pk>/', edit_product, name='edit_product'),
    path('products/formset/', products_formset_view, name='products_formset'),
    path('icecream/', icecream_form, name='icecream'),
    path('add26/', add_dz26, name='add_dz26'),
    path('addcourse/', add_course, name='add_course'),
    path('coursemodel/', course_modelformset, name="course_modelformset"),
    path('coursewithlesson/', course_with_lessons_view, name='coursewithlesson'),
    path('productsearch/', productsearchform, name='productsearchform'),
    path('test-transaction/', test_transaction, name='test_transaction'),
    path('vote/', vote_view, name='vote_view'),
    path('files/', list_files, name="list_files" ),
    path('filess/', list_filess, name="list_filess"),
    path('upload/', upload_image, name='upload_image'),
    path("files/upload/", upload_file, name="upload_file"),
    path('files/<str:filename>/', serve_file, name="serve_file"),
    path("photos/", photo_list, name="photo_list"),
    path("photos/upload/", upload_photo, name = "upload_photo"),
    path("photos/delete/<int:pk>/", delete_photo, name="delete_photo"),
    path("lowlevel/", upload_low_level, name="upload_low_level"),
    path("check_product/<str:signed_id>/", check_product, name='check_product'),
    path("api/products/", create_product, name='create_product'),
    path("api/products2/", ProductListCreateView.as_view(), name='product_list_create_view'),
    path("product_list_cached/", product_list_cached, name='product_list_cached'),
    path("api/user_list/", user_list, name="user_list"),
    path("api/tasks/<int:pk>/", task_detail, name="task_detail"),
    path("api/tasks/", task_list, name="task_list"),
    path("api/createuser/", create_user, name="create_user"),
    path("api/taskdetail/<int:pk>", TaskDetailView.as_view(), name="detail"),
    path("api/tasks_meta/", TaskMetaView.as_view(), name="task_meta"),
    path("api/list/", ProductListView.as_view(), name="product_list"),
    path("api/get_token_manual/", get_token_manual, name='get_token_manual'),
]
